---
apiVersion: tower.ansible.com/v1alpha1
kind: Module
metadata:
  name: "organization:DEMO:permission:admin:project:ansible-devops:team:devops"
  namespace: ansible-tower
spec:
  tower_auth_secret: "tower.victorock.io"
  name: "tower_role"
  parameters:
    organization: "DEMO"
    team: "devops"
    role: "admin"
    project: "ansible-devops"
