apiVersion: tower.ansible.com/v1alpha1
kind: Project
metadata:
  name: netdevops
  namespace: ansible-platform
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: "30s"
spec:
  secret: toweraccess
  config:
    organization: netdevops
    name: '{{ ansible_operator_meta.name }}'
    scm_type: 'git'
    scm_branch: 'dev'
    scm_clean: 'true'
    scm_update_on_launch: 'false'
    scm_url: https://github.com/victorock/ansible-netops
