---
apiVersion: tower.ansible.com/v1alpha1
kind: Module
metadata:
  name: "DEMO"
  namespace: "ansible-tower"
spec:
  tower_auth_secret: "tower.victorock.io"
  name: "tower_organization"
  parameters:
    name: "DEMO"
    description: "DEMO"
    state: "present"
