apiVersion: tower.ansible.com/v1alpha1
kind: User
metadata:
  name: netdevops
  namespace: ansible-platform
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: "30"
spec:
  secret: toweraccess
  config:
    username: '{{ ansible_operator_meta.name }}'
    first_name: '{{ ansible_operator_meta.name }}'
    last_name: 'NetDevOps'
    password: changeme
