apiVersion: tower.ansible.com/v1alpha1
kind: Credential
metadata:
  name: myuser
  namespace: ansible-platform
  labels:
    organization: netdevops
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: "30s"
spec:
  secret: toweraccess
  config:
    organization: netdevops
    name: '{{ ansible_operator_meta.name }}'
    credential_type: Machine
    inputs:
      username: myuser
      password: changeme
