apiVersion: tower.ansible.com/v1alpha1
kind: Team
metadata:
  name: netdevops
  namespace: ansible-platform
  labels:
    organization: netdevops
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: "30s"
spec:
  secret: toweraccess
  config:
    organization: netdevops
    name: '{{ ansible_operator_meta.name }}'
