---
apiVersion: tower.ansible.com/v1alpha1
kind: Organization
metadata:
  name: "organization"
  namespace: "ansible-platform"
  labels:
    organization: "default"
spec:
  secret: "toweraccess"
  config:
    name: "{{ ansible_operator_meta.name }}"
