---
apiVersion: tower.ansible.com/v1alpha1
kind: Team
metadata:
  name: "team"
  namespace: "ansible-platform"
  labels:
    organization: "Default"
spec:
  secret: "toweraccess"
  config:
    organization: "Default"
    name: "{{ ansible_operator_meta.name }}"
