---
apiVersion: tower.ansible.com/v1alpha1
kind: Module
metadata:
  name: "DEMO.user.devops"
  namespace: ansible-tower
spec:
  tower_auth_secret: "tower.victorock.io"
  name: "tower_user"
  parameters:
    name: "devops"
    superuser: true
    auditor: false
