---
apiVersion: tower.ansible.com/v1alpha1
kind: Module
metadata:
  name: "organization:DEMO:team:appops"
  namespace: ansible-tower
spec:
  tower_auth_secret: "tower.victorock.io"
  name: "tower_team"
  parameters:
    organization: "DEMO"
    name: "appops"
    description: "appops Team"
