---
apiVersion: tower.ansible.com/v1alpha1
kind: Module
metadata:
  name: "DEMO.team.infraops"
  namespace: ansible-tower
spec:
  tower_auth_secret: "tower.victorock.io"
  name: "tower_team"
  parameters:
    organization: "DEMO"
    name: "infraops"
    description: "InfraOps Team"
---
apiVersion: tower.ansible.com/v1alpha1
kind: Module
metadata:
  name: "DEMO.permission.team.infraops"
  namespace: ansible-tower
spec:
  tower_auth_secret: "tower.victorock.io"
  name: "tower_role"
  parameters:
    organization: "DEMO"
    team: "infraops"
    role: "admin"
    target_team: "infraops"
