---
apiVersion: tower.ansible.com/v1alpha1
kind: Module
metadata:
  name: "DEMO.team.netops"
  namespace: ansible-tower
spec:
  tower_auth_secret: "tower.victorock.io"
  name: "tower_team"
  parameters:
    organization: "DEMO"
    name: "netops"
    description: "netops Team"
    organization: "DEMO"
