apiVersion: tower.ansible.com/v1alpha1
kind: Role
metadata:
  name: netdevops-is-member-of-organization-netdevops
  namespace: ansible-platform
  labels:
    organization: netdevops
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: "30s"
spec:
  secret: toweraccess
  config:
    organization: netdevops
    role: member
    user: netdevops
