apiVersion: tower.ansible.com/v1alpha1
kind: Role
metadata:
  name: team-netdevops-is-admin-of-organization-netdevops
  namespace: ansible-platform
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: "30s"
spec:
  secret: toweraccess
  config:
    organization: netdevops
    role: admin
    team: netdevops
